config = {
    "light_category": "🟢 Пустяк",
    "medium_category": "🟦 Желание",
    "hard_category": "💜 Мечта",
    "cancel": "❌ Отмена",
    "accept": "✅ Подтвердить",
    "execute_wish": "✅ Буду исполнять",
    "execute": "✅🔓",
    "refuse": "❌🔓",
    "forward": "➡️",
    "back": "⬅️",
    "step_back": "↩️",
    "edit": "✍️",
    "delete": "🚮",
    "realize": "🎁",
    "executed": "🎁 Это желание кто-то выполняет!",
    "not_executed": "Это желание еще никто не выполняет",
    "unsubscribe": "❌",
    "on": "✅ Включено",
    "off": "❌ Выключено",
    "private": "👀 Приватность",
    "notifications": "🛎 Уведомления",
    "wish_for_all": "🌎 Доступ всем",
    "clear_chat": "🗑 Автоочистка чата"
}
